[target.'cfg(target_os = "macos")']
rustflags = ["-C", "panic=abort", "-C", "link-args=-e __start -static -nostartfiles", "-Z", "panic_abort_tests"]

[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins"]

[build]
target = "x86_64-blog_os.json"

[target.'cfg(target_os = "none")']
runner = "bootimage runner"
